### ISSUE TITLE
TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by Krillle** [ahs502/key-file-storage#10]
The line same as in readme throws an error:
 `const kfs = require("key-file-storage")('/var/lib/homebridge');`

It throws: 
`TypeError: require(...) is not a function`

I tried several approaches, this error stays. What can be wrong?

**Comment by ahs502** [comment]
Hi, Christian.

Thanks for the report.
I'll take a look as soon as I can and let you know.

Best regards,

Hessamoddin A Shokravi
+98 933 777 0720

**Comment by ahs502** [comment]
By the way, it seems to me you're probably running the library in an
environment that doesn't have *require()* available as a global method.
Will you please tell me more about your setup?
For example, if you're developing a frontend or backend app, or how you run
your code.
Thanks in advance.

Hessamoddin A Shokravi
+98 933 777 0720

**Comment by Krillle** [comment]
Hi Hessamoddin. Thanks for looking into it. 

In am using lots of requires. Find my source code here: https://github.com/Krillle/homebridge-signalk/blob/signalk-access-token/index.js

It’s a plugin for homebridge, running server sided. 

Regards, Christian

**Comment by ahs502** [comment]
I see.
I believe my guess was wrong, otherwise the error message would have been
like "require is not a function", not "require(...) is not a function".
Please, let me see if there is anything I can do about this.

Hessamoddin A Shokravi
+98 933 777 0720

**Comment by ahs502** [comment]
Will you please try something for me?
Try inspecting the import:

const kfs = require("key-file-storage");

console.log(kfs);


Also, let's check if the function is accessible in another way on your
code, for example:

console.log(kfs.default);

// Or, I don't know, if it is a promise!
kfs.then(console.log);

// Or, anything else that might come to your mind.

I would appreciate it if you please try those and let me know about the
result.
You'll be a great help refining and improving the package.

Hessamoddin A Shokravi
+98 933 777 0720

**Comment by Krillle** [comment]
I implemented the logging:
```
const keyFileStorage = require("key-file-storage");
log("kfs:", keyFileStorage);
log("kfs.default:", keyFileStorage.default);
keyFileStorage.then(log)
```

This is the output:
```
kfs: { default: [Function: keyFileStorage] }
kfs.default: [Function: keyFileStorage]
TypeError: keyFileStorage.then is not a function
```

It seems to me, the problem is in my code. Are I doing something wrong with the brackets in:

`const kfs = require("key-file-storage")('/var/lib/homebridge');`

**Comment by ahs502** [comment]
Interesting, I'll see into this further.
But, as you may already noticed, you may change your code into the
following to make it work:

const kfs = require("key-file-storage")*.default*('/var/lib/homebridge');


Please, proceed with the above line for now, I don't want you to keep being
blocked.

I'll try to figure out in what situations a default export is accessible
via require(...) and in what other situations accessible via
require(...).default and then will fix either the package implementation or
documentation.

Again, I appreciate your time, your feedback, and your help on this matter!
Have a nice day!

Hessamoddin A Shokravi
+98 933 777 0720

**Comment by Krillle** [comment]
Your proposed workaround works out for me:

```
const keyFileStorage = require("key-file-storage");
const kfs = keyFileStorage.default('/var/lib/homebridge');
```

Thank you very much for your kind and fast support.

**Comment by ahs502** [comment]
Anytime, Christian!
You too 👍

Hessamoddin A Shokravi
+98 933 777 0720
