### ISSUE TITLE
I need something  that acts as a fast cache for my node app. Hitting the DB for counters etc can be costly I need something fast. Is this just that?

### ISSUE THREAD

**Issue by tillifywebb** [ahs502/key-file-storage#2]

**Comment by ahs502** [comment]
Yes, It should be.
In fact when I say 'cache', I mean a simple javascript Object including some key-value stored in it.
The simplified caching mechanism is I add a key-value pair into my cache like :

    cache[key] = value;

at the first access, then, when you access some certain key, I simply check for existence of that key in cache object first.
I can't think of a faster way, but suggest you to have a performance test to compare different solutions to make sure yourself.

Best regards!
