### ISSUE TITLE
Can you provide the option to create hidden files?

### ISSUE THREAD

**Issue by ashishnumino** [ahs502/key-file-storage#4]
will it be as simple as attaching `.` to the file before creating? i tried doing that. Works for me 👍

**Comment by ahs502** [comment]
Good idea!
I have not thought about it before...
Yes, that should work!
I shall mention it in the readme file in later releases.
Thank you.

Now, I guess I can ask you something, please let me know if you have any improving idea about these two concerns of mine:

1. The sync and async API of the storage, to be easier and more self-expressive
2. Any implementation suggestion to support transactions (modifying different key-values and commit them all in one atomic action, for example)

Thanks again for reading this far!

**Comment by ashishnumino** [comment]
Thank you. I would definitely think on this. I am a beginner.

**Comment by ahs502** [comment]
Good luck with that!

**Comment by ahs502** [comment]
I've added this to the documentation.
