### ISSUE TITLE
Enumerating keys using cache

### ISSUE THREAD

**Issue by PeteBa** [ahs502/key-file-storage#5]
I am using `key-file-storage` to cache/persist around 2,000 key/values using unlimited cache setting. In order to iterate over the keys i can only see `let k = kvs["/"]` available. Unfortunately, this does not use the cache but rather goes out to the filesystem. This is a big hit on performance with c.2,000 files. Is there a way of extracting an enumerated list of keys from the cache when available ?

Thanks for the module as it is working great (except for iterating cached keys).

**Comment by ahs502** [comment]
Hi! Thanks for using `key-file-storage`!
I'll check and response as soon as possible.

**Comment by ahs502** [comment]
Caching is applied to collection queries too.
Just upgrade the `key-file-storage` to version **`2.2.3`** *(Edited: ~`2.2.2`~)*.

Thank you for waiting.
Please reopen this issue if it is not working as expected.

**Comment by ahs502** [comment]
Sorry, I think it is your duty to close this issue!!
I'll reopen this issue myself, and you may close it if you think it's done.

**Comment by PeteBa** [comment]
Thanks for the change and the effort on this. Unfortunately this is not quite what I has hoping for. Let me explain my use case as that may help.

I am using KeyFileStorage (with unlimited cache) to persist the last 24 hours of a weather data stream that I receive every 30 seconds. I store each received item as `kfs[timestamp, observationObject]`. Every hour, I then use `let k = kfs["/"]` so that I can iterate over all of the stored key/value pairs and delete all of the items with timestamps older than 24 hours using `kfs[timestamp, undefined]`. Looking at the file system, I can see that the old items have been deleted but when I next iterate over the collection, `kfs["/"]` still returns the old items.

Looking at the code, it appears that your are caching the first call to `kfs["/"]` in `querySync` but not modifying the collection cache when items are added/deleted. Perhaps this is the behaviour that you wanted and my use-case is too specific ?

**Comment by ahs502** [comment]
Very good, thanks for the details.
I'll dive into this ASAP.

**Comment by ahs502** [comment]
A completely separated cache is implemented for collections.
This cache will get updated by accessing individual keys.
Please update your `key-file-storage` version and see if it does the job now.
